services:
  qdrant:
    image: qdrant/qdrant
    expose:
      #portas para dev apenas
      - 6333
    ports:  #para acessar no navegador local utilize
      - 6333:6333
    volumes: 
      - ./qdrant_storage:/qdrant/storage:z
  web:
    image: enyalius/fulldev
    environment:
      - WEBAPP_ROOT=frontend
      #o padrão é 1000 mas se quiser rodar um outro usuário veja o id usando o comando: id -u 
      - WEBAPP_USER_ID=${USER_ID:-1000}
    volumes:
      - ./:/app
    expose:
      - 80
      - 443
    ports:
      - 80:80
  server:
    build:
      dockerfile: ./Dockerfile
      context: . 
    #image: enyalius/llm-dev #ver de usar uma imagem completa com o vini
    environment:
      - OLLAMA_URL=${OLLAMA_URL:-http://192.168.100.35:11434} #alterar para o IP do seu computador modo de leitura de imagens
    volumes:
      - ./:/app
    expose:
      - 5508
    ports:
      - 5508:5508
    extra_hosts: #Se o Ollama estiver rodando localmente
      - "host.docker.internal:host-gateway"
    command: python3 -B ./service.py
   